### ISSUE TITLE
Toggle Edit

### ISSUE THREAD

**Issue by alicialycan** [TimeLineHelper/calendar-app#22]
Having a hard time debugging the toggleEdit error, went through code and followed it from props. Tried several things but no luck. Branch is: al-day06

Error message: Uncaught TypeError: _this.props.toggleEdit is not a function
    at TaskForm._this.handleSubmit (taskForm.js:37)

Recreate the error by running 'npm start' in the backend folder in our app. Then click on the big update button.

Thanks!

**Comment by geluso** [comment]
It looks to me like you have the TaskForm component used in two different places. One of them passes a toggleEdit function, the other one does not.

This one has it:
https://github.com/TimeLineHelper/calendar-app/blob/al-day06/backend/public/src/components/tasks/taskItem.js#L64

This one does not: 
https://github.com/TimeLineHelper/calendar-app/blob/al-day06/backend/public/src/components/timeline.js#L54

It makes sense that the one creating the tasks would not have a toggle edit because they haven't been created yet.

One idea is to wrap the call to `toggleEdit` in an if statement that checks to see if it's actually there before executing it.

```
if (this.props.toggleEdit) {
  this.props.toggleEdit();
}
```

**Comment by geluso** [comment]
Oops. I was wrong. It was just that the TaskForm accepts a string either "Create" or "Update." Later in your code the form tells what itself is by looking at that string. But it compared that to "create" with a lowercase "c." Try using .toLowerCase() there and it should all work out.

    if (this.props.buttonText.toLowerCase() === 'create') {
